fav_animal = input("What is your favorite animal?\n")
reason = input("Why do you like " + fav_animal + "?\n")
location = input("Where can " + fav_animal + " be found?\n")
diet = input("What does " + fav_animal + " eat?\n")
favorite_fact = input("What is your favorite fact about " + fav_animal + "?\n")
movement = input("How does " + fav_animal + " move around?\n")
endangered = input("Is " + fav_animal + " endangered? (yes/no)\n")
invasive = input("Is " + fav_animal + " an invasive species? (yes/no)\n")
sleep1 = input("Does " + fav_animal + " sleep during the day or night?\n")
sleep = input("How many hours does " + fav_animal + " sleep per day?\n")

print("\nYour favorite animal is: " + fav_animal)
print("You like " + fav_animal + " because: " + reason)
print("You can find " + fav_animal + " in: " + location)
print("The diet of " + fav_animal + " consists of: " + diet)
print("Your favorite fact about " + fav_animal + " is: " + favorite_fact)
print("The way " + fav_animal + " moves around is: " + movement)
print("Is " + fav_animal + " endangered? " + endangered)
print("Is " + fav_animal + " an invasive species? " + invasive)
print("Does " + fav_animal + " sleep during the day or night? " + sleep1)
print("How many hours does " + fav_animal + " sleep per day? " + sleep)